# Generated by Django 5.1.5 on 2025-03-30 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.PositiveSmallIntegerField()),
                ('end_hour', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_hour'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_hour__gte', 0), ('start_hour__lte', 23)), name='valid_start_hour'), models.CheckConstraint(condition=models.Q(('end_hour__gte', 1), ('end_hour__lte', 24)), name='valid_end_hour'), models.CheckConstraint(condition=models.Q(('end_hour__gt', models.F('start_hour'))), name='end_after_start')],
            },
        ),
    ]
