# Generated by Django 5.1.5 on 2025-03-30 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='valid_start_hour',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='valid_end_hour',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('start_hour__gte', 6), ('start_hour__lte', 21)), name='valid_start_hour'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('end_hour__gte', 7), ('end_hour__lte', 22)), name='valid_end_hour'),
        ),
    ]
